CREATE TABLE Clientes (
    Codigo INTEGER NOT NULL PRIMARY KEY,
    Nome VARCHAR(100),
    CPF VARCHAR(14),
    Endereco VARCHAR(200),
    Cidade VARCHAR(70),
    Estado VARCHAR(2)
);

CREATE GENERATOR GEN_CLIENTES_CODIGO_ID;

SET TERM ^ ;
CREATE TRIGGER TRG_CLIENTES_CODIGO_BI FOR Clientes
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.Codigo IS NULL OR NEW.Codigo = 0) THEN
    NEW.Codigo = GEN_ID(GEN_CLIENTES_CODIGO_ID, 1);
END^
SET TERM ; ^